# schema: ./_schema.ts
- traP Collection:
  title: traP Collection
  description: traPで開発したゲームを管理・配信するためのサービスです。バックエンドの開発・運用を行っています。
  heroImage: "/products/trap-collection-logo.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - Github:
      name: GitHub
      url: https://github.com/traPtitech/trap-collection-server
      icon: codicon:github
      primary: true

- isu-isu-h:
  title: isu-isu-h
  description: "ISUCON(https://isucon.net)での改善をスムーズに行うためのツール群です。「いすいすえいち」と読みます。"
  heroImage: "/products/isu-isu-h.png"
  tags:
    - ISUCON
    - Ansible
    - Docker
  links:
    - Github:
      name: GitHub
      url: https://github.com/reactive-futakotamagawa/isu-isu-h-13
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2047/
      icon: ri:article-line
      primary: false

- hakka-mura:
  title: 発火村（はっかむら）
  description: traPのハッカソンで作った、絶対に炎上する新世代SNSです。バックエンドの開発を行いました。
  heroImage: "/products/hakka-mura.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/traP-jp/hakka-mura?ref=ikura-hamu.work
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2255/
      icon: ri:article-line

- postQard:
  title: postQard
  description: traPのハッカソンで作った、年賀状投稿サービスです。Next.jsのApp Routerによるフロントエンドの開発を行いました。
  heroImage: "/products/postQard.png"
  tags:
    - Next.js
    - traP
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/traP-jp/h23w_01-frontend
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/1983/
      icon: ri:article-line

- いかしかめかアクティビティズ:
  title: いかしかめかアクティビティズ
  description: traPのハッカソンで作った、部内SNSのメッセージを使ったブラウザゲームです。バックエンドの開発を行いました。
  heroImage: "/products/ika-shika-meka.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/traP-jp/h23s_01
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/1899
      icon: ri:article-line

- なろう講習会:
  title: Webエンジニアになろう講習会
  description: traPで毎年開催される、Web開発の基礎を扱う講習会です。2023年度の講師を務め、資料作成などを行いました。
  heroImage: "/products/naro.png"
  tags:
    - Web
    - traP
  links:
    - 資料:
      name: 資料
      url: https://traptitech.github.io/naro-text
      icon: ri:file-text-line
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/1969/
      icon: ri:article-line
      primary: false
