# schema: ./_schema.ts
- traP Collection:
  title: traP Collection
  description: traPで開発したゲームを管理・配信するためのサービスです。バックエンドの開発・運用を行っています。
  heroImageContent: "./products/trap-collection-logo.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - Github:
      name: GitHub
      url: https://github.com/traPtitech/trap-collection-server
      icon: codicon:github
      primary: true

- isu-isu-h:
  title: isu-isu-h
  description: "ISUCON(https://isucon.net)での改善をスムーズに行うためのツール群です。「いすいすえいち」と読みます。"
  heroImageContent: "./products/isu-isu-h.png"
  tags:
    - ISUCON
    - Ansible
    - Docker
  links:
    - Github:
      name: GitHub
      url: https://github.com/reactive-futakotamagawa/isu-isu-h-13
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2047/
      icon: ri:article-line
      primary: false

- hakka-mura:
  title: 発火村（はっかむら）
  description: traPのハッカソンで作った、絶対に炎上する新世代SNSです。バックエンドの開発を行いました。
  heroImageContent: "./products/hakka-mura.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/traP-jp/hakka-mura?ref=ikura-hamu.work
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2255/
      icon: ri:article-line

- card:
  title: 名刺 TUI
  description: Go で作った TUI の名刺です。 bubbletea というライブラリを使って実装されています。
  tags:
    - Go
    - TUI
  heroImageContent: "./products/card.gif"
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/ikura-hamu/card
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2668/
      icon: ri:article-line

- hasTen:
  title: hasTen
  description: traP のハッカソンで作った、make 10 パズルをベースにしたオンライン対戦ゲームです。
  heroImageContent: "./products/hasTen.png"
  tags:
    - Go
    - WebSocket
    - ゲーム
    - traP
  links:
    - GitHub:
      name: GitHub
      url: https://github.com/traP-jp/h25s_15
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2617/
      icon: ri:article-line
