# schema: ./_schema.ts
- traP Collection:
  title: traP Collection
  description: traPで開発したゲームを管理・配信するためのサービスです。バックエンドの開発・運用を行っています。
  heroImage: "src/images/products/trap-collection-logo.png"
  tags:
    - Go
    - MariaDB
    - traP
  links:
    - Github:
      name: GitHub
      url: https://github.com/traPtitech/trap-collection-server
      icon: codicon:github
      primary: true
- isu-isu-h:
  title: isu-isu-h
  description: 'ISUCON(https://isucon.net)での改善をスムーズに行うためのツール群です。「いすいすえいち」と読みます。'
  heroImage: "src/images/products/isu-isu-h.png"
  tags: 
    - ISUCON
    - Ansible
    - Docker
  links:
    - Github:
      name: GitHub
      url: https://github.com/reactive-futakotamagawa/isu-isu-h-13
      icon: codicon:github
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/2047/
      icon: ri:article-line
      primary: false
- なろう講習会:
  title: Webエンジニアになろう講習会
  description: traPで毎年開催される、Web開発の基礎を扱う講習会です。2023年度の講師を務め、資料作成などを行いました。
  heroImage: "src/images/products/naro.png"
  tags:
    - Web
    - traP
  links:
    - 資料:
      name: 資料
      url: https://traptitech.github.io/naro-text
      icon: ri:file-text-line
      primary: true
    - ブログ:
      name: ブログ
      url: https://trap.jp/post/1969/
      icon: ri:article-line
      primary: false